dist: trusty

git:
  depth: 500

language: node_js

node_js:
  - "6"

before_install:
  - wget https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central/jsshell-linux-x86_64.zip
  - unzip jsshell-linux-x86_64.zip -d spidermoney
  - sudo apt-get install -y libjavascriptcoregtk-3.0-bin
  - wget https://aka.ms/chakracore/cc_linux_x64_1_8_1 -O chakra-core.tar.gz
  - tar xvzf chakra-core.tar.gz
  - wget https://github.com/oracle/graal/releases/download/vm-1.0.0-rc6/graalvm-ce-1.0.0-rc6-linux-amd64.tar.gz
  - tar xzf graalvm-ce-1.0.0-rc6-linux-amd64.tar.gz

before_script:
  - script/bootstrap
  - script/uberjar
  - mkdir -p builds/out-adv
  - bin/cljsc src/test/cljs "{:optimizations :advanced
                              :output-wrapper true
                              :verbose true
                              :compiler-stats true
                              :parallel-build true
                              :output-dir \"builds/out-adv\"
                              :npm-deps {:lodash \"4.17.4\"}
                              :closure-warnings {:non-standard-jsdoc :off :global-this :off}
                              :language-in :es6
                              :language-out :es5
                              :install-deps true
                              :foreign-libs [{:file \"src/test/cljs/calculator_global.js\"
                                              :provides [\"calculator\"]
                                              :global-exports {calculator Calculator}}
                                             {:file \"src/test/cljs/es6_dep.js\"
                                              :module-type :es6
                                              :provides [\"es6_calc\"]}
                                             {:file \"src/test/cljs/calculator.js\"
                                              :module-type :commonjs
                                              :provides [\"calculator\"]}
                                             {:file \"src/test/cljs/es6_default_hello.js\"
                                              :provides [\"es6_default_hello\"]
                                              :module-type :es6}]}" > builds/out-adv/core-advanced-test.js

script:
  - lein test
  - jsc builds/out-adv/core-advanced-test.js | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
  - ./spidermoney/js -f builds/out-adv/core-advanced-test.js | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
  - jjs builds/out-adv/core-advanced-test.js | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
  - ./ChakraCoreFiles/bin/ch builds/out-adv/core-advanced-test.js | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
  - ./graalvm-ce-1.0.0-rc6/bin/js builds/out-adv/core-advanced-test.js | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
  - script/test-self-host | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
  - script/test-self-parity | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
  - script/test-cli node | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
  - script/test-cli nashorn | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
  - script/test-cli rhino | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
  - PATH=`pwd`/graalvm-ce-1.0.0-rc6/bin:$PATH script/test-cli graaljs | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
